### ISSUE TITLE
EventRunner test - service to service auth

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/eventrunner#87]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrunner-api
  namespace: eventrunner
spec:
  template:
    spec:
      containers:
        - name: api
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
```
