### ISSUE TITLE
Service mesh integration

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/eventrunner#89]
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: eventrunner-auth
  namespace: eventrunner
spec:
  selector:
    matchLabels:
      app: eventrunner-api
  jwtRules:
  - issuer: "spiffe://tunnel.threadr.ai"
    jwksUri: "spiffe://tunnel.threadr.ai/.well-known/jwks.json"
```
